apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ansiblehelloworlds.ansible-hello-world.operator.com
spec:
  group: ansible-hello-world.operator.com
  names:
    kind: AnsibleHelloWorld
    listKind: AnsibleHelloWorldList
    plural: ansiblehelloworlds
    singular: ansiblehelloworld
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
