apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kibana
spec:
  secretName: kibana-cert
  commonName: "kibana.gcloud.lominorama.com"
  dnsNames:
    - kibana.gcloud.lominorama.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
